obj-y += msc_disk.o
obj-y += hal_adapter/board.o
obj-y += hal_adapter/family.o
obj-y += usb_descriptors.o
obj-y += usb_protocol.o
EXTRA_CFLAGS += -Iapp/cdc_msc/hal_adapter
EXTRA_CFLAGS += -Iapp/cdc_msc
EXTRA_CFLAGS += -Ithird_party/tinyusb