# Object files to build into built-in.o
obj-y += your_app.o
obj-y += mpu6050/
obj-y += aiNet/
obj-y += mobile_communication/
obj-y += w25qxx/
obj-y += cdc_msc/

EXTRA_CFLAGS += -Iapp/mpu6050
EXTRA_CFLAGS += -Iapp/aiNet/inc
EXTRA_CFLAGS += -IAI/Inc