# Object files to build into built-in.o
obj-y += osal_event_ll.o
obj-y += osal_mem_ll.o
obj-y += osal_mutex_ll.o
obj-y += osal_queue_ll.o
obj-y += osal_sem_ll.o
obj-y += osal_system_ll.o
obj-y += osal_task_ll.o
obj-y += osal_timer_ll.o