# Object files to build into built-in.o
obj-y += osal_event.o
obj-y += osal_mem.o
obj-y += osal_mutex.o
obj-y += osal_queue.o
obj-y += osal_sem.o
obj-y += osal_task.o
obj-y += osal_timer.o
obj-y += osal_system.o

EXTRA_CFLAGS += -Iosal/rtthread