/**
 * @file    irq_handlers_stm32h5_calculated.h
 * @brief   STM32H5 Interrupt Handler Definitions with calculated values (Weak Symbols)
 *
 * This file defines weak interrupt handler functions for all STM32H5 interrupts.
 * Each handler calls the framework's unified interrupt handler with the calculated IRQ number.
 *
 * @note    Application can override any handler by defining a strong symbol.
 */

#ifndef IRQ_HANDLERS_STM32H5_CALCULATED_H
#define IRQ_HANDLERS_STM32H5_CALCULATED_H

#include <stdint.h>

/*------------------------------------------------------------------------------
 * Forward Declarations
 *----------------------------------------------------------------------------*/
void framework_irq_handler(uint32_t irq_num);
void Default_Handler(void);

/*------------------------------------------------------------------------------
 * Macro to Define Weak Interrupt Handler
 *----------------------------------------------------------------------------*/
#define FRAMEWORK_DEFINE_IRQ_HANDLER(name, irq_num) \
    void __attribute__((weak)) name(void)           \
    {                                               \
        framework_irq_handler(irq_num);             \
    }

/*------------------------------------------------------------------------------
 * External Interrupt Handlers (Weak Definitions)
 *----------------------------------------------------------------------------*/

/* WWDG (IRQ 15) */
FRAMEWORK_DEFINE_IRQ_HANDLER(WWDG_IRQHandler, 15)

/* PVD/AVD (IRQ 16) */
FRAMEWORK_DEFINE_IRQ_HANDLER(PVD_AVD_IRQHandler, 16)

/* RTC non-secure (IRQ 17) */
FRAMEWORK_DEFINE_IRQ_HANDLER(RTC_IRQHandler, 17)

/* RTC secure (IRQ 18) */
FRAMEWORK_DEFINE_IRQ_HANDLER(RTC_S_IRQHandler, 18)

/* TAMP (IRQ 19) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TAMP_IRQHandler, 19)

/* RAMCFG (IRQ 20) */
FRAMEWORK_DEFINE_IRQ_HANDLER(RAMCFG_IRQHandler, 20)

/* FLASH non-secure (IRQ 21) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FLASH_IRQHandler, 21)

/* FLASH secure (IRQ 22) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FLASH_S_IRQHandler, 22)

/* GTZC (IRQ 23) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GTZC_IRQHandler, 23)

/* RCC non-secure (IRQ 24) */
FRAMEWORK_DEFINE_IRQ_HANDLER(RCC_IRQHandler, 24)

/* RCC secure (IRQ 25) */
FRAMEWORK_DEFINE_IRQ_HANDLER(RCC_S_IRQHandler, 25)

/* EXTI Line0 (IRQ 26) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI0_IRQHandler, 26)

/* EXTI Line1 (IRQ 27) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI1_IRQHandler, 27)

/* EXTI Line2 (IRQ 28) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI2_IRQHandler, 28)

/* EXTI Line3 (IRQ 29) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI3_IRQHandler, 29)

/* EXTI Line4 (IRQ 30) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI4_IRQHandler, 30)

/* EXTI Line5 (IRQ 31) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI5_IRQHandler, 31)

/* EXTI Line6 (IRQ 32) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI6_IRQHandler, 32)

/* EXTI Line7 (IRQ 33) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI7_IRQHandler, 33)

/* EXTI Line8 (IRQ 34) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI8_IRQHandler, 34)

/* EXTI Line9 (IRQ 35) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI9_IRQHandler, 35)

/* EXTI Line10 (IRQ 36) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI10_IRQHandler, 36)

/* EXTI Line11 (IRQ 37) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI11_IRQHandler, 37)

/* EXTI Line12 (IRQ 38) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI12_IRQHandler, 38)

/* EXTI Line13 (IRQ 39) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI13_IRQHandler, 39)

/* EXTI Line14 (IRQ 40) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI14_IRQHandler, 40)

/* EXTI Line15 (IRQ 41) */
FRAMEWORK_DEFINE_IRQ_HANDLER(EXTI15_IRQHandler, 41)

/* GPDMA1 Channel 0 (IRQ 42) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel0_IRQHandler, 42)

/* GPDMA1 Channel 1 (IRQ 43) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel1_IRQHandler, 43)

/* GPDMA1 Channel 2 (IRQ 44) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel2_IRQHandler, 44)

/* GPDMA1 Channel 3 (IRQ 45) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel3_IRQHandler, 45)

/* GPDMA1 Channel 4 (IRQ 46) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel4_IRQHandler, 46)

/* GPDMA1 Channel 5 (IRQ 47) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel5_IRQHandler, 47)

/* GPDMA1 Channel 6 (IRQ 48) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel6_IRQHandler, 48)

/* GPDMA1 Channel 7 (IRQ 49) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA1_Channel7_IRQHandler, 49)

/* IWDG (IRQ 50) */
FRAMEWORK_DEFINE_IRQ_HANDLER(IWDG_IRQHandler, 50)

/* ADC1 (IRQ 52) */
FRAMEWORK_DEFINE_IRQ_HANDLER(ADC1_IRQHandler, 52)

/* DAC1 (IRQ 53) */
FRAMEWORK_DEFINE_IRQ_HANDLER(DAC1_IRQHandler, 53)

/* FDCAN1 IT0 (IRQ 54) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FDCAN1_IT0_IRQHandler, 54)

/* FDCAN1 IT1 (IRQ 55) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FDCAN1_IT1_IRQHandler, 55)

/* TIM1 Break (IRQ 56) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM1_BRK_IRQHandler, 56)

/* TIM1 Update (IRQ 57) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM1_UP_IRQHandler, 57)

/* TIM1 Trigger and Commutation (IRQ 58) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM1_TRG_COM_IRQHandler, 58)

/* TIM1 Capture Compare (IRQ 59) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM1_CC_IRQHandler, 59)

/* TIM2 (IRQ 60) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM2_IRQHandler, 60)

/* TIM3 (IRQ 61) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM3_IRQHandler, 61)

/* TIM4 (IRQ 62) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM4_IRQHandler, 62)

/* TIM5 (IRQ 63) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM5_IRQHandler, 63)

/* TIM6 (IRQ 64) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM6_IRQHandler, 64)

/* TIM7 (IRQ 65) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM7_IRQHandler, 65)

/* I2C1 Event (IRQ 66) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C1_EV_IRQHandler, 66)

/* I2C1 Error (IRQ 67) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C1_ER_IRQHandler, 67)

/* I2C2 Event (IRQ 68) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C2_EV_IRQHandler, 68)

/* I2C2 Error (IRQ 69) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C2_ER_IRQHandler, 69)

/* SPI1 (IRQ 70) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SPI1_IRQHandler, 70)

/* SPI2 (IRQ 71) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SPI2_IRQHandler, 71)

/* SPI3 (IRQ 72) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SPI3_IRQHandler, 72)

/* USART1 (IRQ 73) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USART1_IRQHandler, 73)

/* USART2 (IRQ 74) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USART2_IRQHandler, 74)

/* USART3 (IRQ 75) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USART3_IRQHandler, 75)

/* UART4 (IRQ 76) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UART4_IRQHandler, 76)

/* UART5 (IRQ 77) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UART5_IRQHandler, 77)

/* LPUART1 (IRQ 78) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPUART1_IRQHandler, 78)

/* LPTIM1 (IRQ 79) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPTIM1_IRQHandler, 79)

/* TIM8 Break (IRQ 80) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM8_BRK_IRQHandler, 80)

/* TIM8 Update (IRQ 81) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM8_UP_IRQHandler, 81)

/* TIM8 Trigger and Commutation (IRQ 82) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM8_TRG_COM_IRQHandler, 82)

/* TIM8 Capture Compare (IRQ 83) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM8_CC_IRQHandler, 83)

/* ADC2 (IRQ 84) */
FRAMEWORK_DEFINE_IRQ_HANDLER(ADC2_IRQHandler, 84)

/* LPTIM2 (IRQ 85) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPTIM2_IRQHandler, 85)

/* TIM15 (IRQ 86) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM15_IRQHandler, 86)

/* TIM16 (IRQ 87) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM16_IRQHandler, 87)

/* TIM17 (IRQ 88) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM17_IRQHandler, 88)

/* USB_DRD_FS (IRQ 89) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USB_DRD_FS_IRQHandler, 89)

/* CRS (IRQ 90) */
FRAMEWORK_DEFINE_IRQ_HANDLER(CRS_IRQHandler, 90)

/* UCPD1 (IRQ 91) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UCPD1_IRQHandler, 91)

/* FMC (IRQ 92) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FMC_IRQHandler, 92)

/* OCTOSPI1 (IRQ 93) */
FRAMEWORK_DEFINE_IRQ_HANDLER(OCTOSPI1_IRQHandler, 93)

/* SDMMC1 (IRQ 94) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SDMMC1_IRQHandler, 94)

/* I2C3 Event (IRQ 95) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C3_EV_IRQHandler, 95)

/* I2C3 Error (IRQ 96) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C3_ER_IRQHandler, 96)

/* SPI4 (IRQ 97) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SPI4_IRQHandler, 97)

/* SPI5 (IRQ 98) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SPI5_IRQHandler, 98)

/* SPI6 (IRQ 99) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SPI6_IRQHandler, 99)

/* USART6 (IRQ 100) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USART6_IRQHandler, 100)

/* USART10 (IRQ 101) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USART10_IRQHandler, 101)

/* USART11 (IRQ 102) */
FRAMEWORK_DEFINE_IRQ_HANDLER(USART11_IRQHandler, 102)

/* SAI1 (IRQ 103) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SAI1_IRQHandler, 103)

/* SAI2 (IRQ 104) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SAI2_IRQHandler, 104)

/* GPDMA2 Channel 0 (IRQ 105) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel0_IRQHandler, 105)

/* GPDMA2 Channel 1 (IRQ 106) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel1_IRQHandler, 106)

/* GPDMA2 Channel 2 (IRQ 107) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel2_IRQHandler, 107)

/* GPDMA2 Channel 3 (IRQ 108) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel3_IRQHandler, 108)

/* GPDMA2 Channel 4 (IRQ 109) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel4_IRQHandler, 109)

/* GPDMA2 Channel 5 (IRQ 110) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel5_IRQHandler, 110)

/* GPDMA2 Channel 6 (IRQ 111) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel6_IRQHandler, 111)

/* GPDMA2 Channel 7 (IRQ 112) */
FRAMEWORK_DEFINE_IRQ_HANDLER(GPDMA2_Channel7_IRQHandler, 112)

/* UART7 (IRQ 113) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UART7_IRQHandler, 113)

/* UART8 (IRQ 114) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UART8_IRQHandler, 114)

/* UART9 (IRQ 115) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UART9_IRQHandler, 115)

/* UART12 (IRQ 116) */
FRAMEWORK_DEFINE_IRQ_HANDLER(UART12_IRQHandler, 116)

/* SDMMC2 (IRQ 117) */
FRAMEWORK_DEFINE_IRQ_HANDLER(SDMMC2_IRQHandler, 117)

/* FPU (IRQ 118) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FPU_IRQHandler, 118)

/* ICACHE (IRQ 119) */
FRAMEWORK_DEFINE_IRQ_HANDLER(ICACHE_IRQHandler, 119)

/* DCACHE1 (IRQ 120) */
FRAMEWORK_DEFINE_IRQ_HANDLER(DCACHE1_IRQHandler, 120)

/* ETH (IRQ 121) */
FRAMEWORK_DEFINE_IRQ_HANDLER(ETH_IRQHandler, 121)

/* ETH_WKUP (IRQ 122) */
FRAMEWORK_DEFINE_IRQ_HANDLER(ETH_WKUP_IRQHandler, 122)

/* DCMI_PSSI (IRQ 123) */
FRAMEWORK_DEFINE_IRQ_HANDLER(DCMI_PSSI_IRQHandler, 123)

/* FDCAN2 IT0 (IRQ 124) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FDCAN2_IT0_IRQHandler, 124)

/* FDCAN2 IT1 (IRQ 125) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FDCAN2_IT1_IRQHandler, 125)

/* CORDIC (IRQ 126) */
FRAMEWORK_DEFINE_IRQ_HANDLER(CORDIC_IRQHandler, 126)

/* FMAC (IRQ 127) */
FRAMEWORK_DEFINE_IRQ_HANDLER(FMAC_IRQHandler, 127)

/* DTS (IRQ 128) */
FRAMEWORK_DEFINE_IRQ_HANDLER(DTS_IRQHandler, 128)

/* RNG (IRQ 129) */
FRAMEWORK_DEFINE_IRQ_HANDLER(RNG_IRQHandler, 129)

/* HASH (IRQ 132) */
FRAMEWORK_DEFINE_IRQ_HANDLER(HASH_IRQHandler, 132)

/* CEC (IRQ 134) */
FRAMEWORK_DEFINE_IRQ_HANDLER(CEC_IRQHandler, 134)

/* TIM12 (IRQ 135) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM12_IRQHandler, 135)

/* TIM13 (IRQ 136) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM13_IRQHandler, 136)

/* TIM14 (IRQ 137) */
FRAMEWORK_DEFINE_IRQ_HANDLER(TIM14_IRQHandler, 137)

/* I3C1 Event (IRQ 138) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I3C1_EV_IRQHandler, 138)

/* I3C1 Error (IRQ 139) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I3C1_ER_IRQHandler, 139)

/* I2C4 Event (IRQ 140) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C4_EV_IRQHandler, 140)

/* I2C4 Error (IRQ 141) */
FRAMEWORK_DEFINE_IRQ_HANDLER(I2C4_ER_IRQHandler, 141)

/* LPTIM3 (IRQ 142) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPTIM3_IRQHandler, 142)

/* LPTIM4 (IRQ 143) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPTIM4_IRQHandler, 143)

/* LPTIM5 (IRQ 144) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPTIM5_IRQHandler, 144)

/* LPTIM6 (IRQ 145) */
FRAMEWORK_DEFINE_IRQ_HANDLER(LPTIM6_IRQHandler, 145)

#endif /* IRQ_HANDLERS_STM32H5_CALCULATED_H */
