# Object files to build into built-in.o
obj-y += platform_gpio_driver.o
obj-y += platform_timer_driver.o
obj-y += platform_uart_driver.o
obj-y += platform_system_driver.o

EXTRA_CFLAGS += -Ihal/stm32h5