# Object files to build into built-in.o
obj-y += hal_gpio.o
obj-y += hal_timer.o
obj-y += hal_uart.o
obj-y += hal_system.o
obj-y += hal_iic.o
obj-y += hal_xspi.o
obj-y += hal_usb.o

EXTRA_CFLAGS += -Imiddleware/hal/stm32h5
EXTRA_CFLAGS += -Iframework/config